// Generated by scripts/generate-mcp-schema.mjs. Do not edit by hand.
export const applicationMcpSchemaManifest = {
  schemaSha256:
    "4937d750390ac210fa6b9ce88000885d87128f0521038e18f1a4618cc31a4df1",
  schemaVersion: 9,
  toolCount: 31,
  tools: [
    {
      name: "get_tracker_context",
      schemaSha256:
        "1af96f567c6ff545efab82a8839a689979fba1767b939c37eb71e9d166b14a27",
    },
    {
      name: "get_connector_schema_status",
      schemaSha256:
        "81e1d50aa1240d64a013cfc05ffff4efb1db7e4f9396279085ebf3eea6e2b633",
    },
    {
      name: "get_job_search_summary",
      schemaSha256:
        "5eb7e6a956eb8bea6910803275f48c2a6b3bfb9f5be3831bfb2c31f93f48b2ff",
    },
    {
      name: "list_applications",
      schemaSha256:
        "b733a3ae8501112ff170c53718f79f7217335f57a7d75f36cd3f27c4a646a942",
    },
    {
      name: "get_application",
      schemaSha256:
        "1b53f09f760a1b69fabf55207e604e47eb5e7dcf21b67e4450782df69070ead8",
    },
    {
      name: "list_unlinked_applications",
      schemaSha256:
        "5ec64a843a14055035f1645ef5a520b37f8fcc42d2e3395db1530e7c1f728e09",
    },
    {
      name: "get_application_data_quality",
      schemaSha256:
        "c9b62bb6d66374df41ea4bf1b8ffae6fa4e7e6c243b6fbaa692acd256af7bbf9",
    },
    {
      name: "audit_duplicate_applications",
      schemaSha256:
        "43b42891de945058fd7d8ae3771e4424d699f25695c728bdad4beaccbd428a01",
    },
    {
      name: "find_duplicate_applications",
      schemaSha256:
        "815a67462ed46b03013b9b417a08cc1c9c1025bf53afe6a62b1d81612f9e3547",
    },
    {
      name: "merge_applications",
      schemaSha256:
        "35b42405759784b3c8618d029fdf425a2e6b5a01d2c170174850915e6a5101a5",
    },
    {
      name: "match_job_application_email",
      schemaSha256:
        "efe1536e9baca7035aab7963b1cb1dfcf158c38fdbdea6587b9819116503487d",
    },
    {
      name: "link_email_evidence",
      schemaSha256:
        "f6de4337c2f0b7713d18401ba9d34a756d6d264728711a1ecc5fe2555a5fcc07",
    },
    {
      name: "reconcile_application_from_evidence",
      schemaSha256:
        "fb1f1fc09a80b047c7ff68c82c8a98ba312405cc474571589a43a2c97fa7185f",
    },
    {
      name: "sync_outlook_email_evidence",
      schemaSha256:
        "085b3e729874ddbce4ea1927f1a9df64c01472dd9be43c871251b67536a7cfa7",
    },
    {
      name: "extract_job_links",
      schemaSha256:
        "a5f87d552d52f1fcfd2ee23a2f81b2d8cdeb8f0e12bcbc94e927821b144f703c",
    },
    {
      name: "resolve_job_links",
      schemaSha256:
        "c0db14d7f90e6154f9130df7e517c5d74a880c913172ac12a02e2c03c64d18b2",
    },
    {
      name: "inspect_job_posting",
      schemaSha256:
        "ba93b8e2e61c88c122fed120fdb6aeb5b8e2106dabc07a4becfdd7c5e1cd7f83",
    },
    {
      name: "get_reference_data",
      schemaSha256:
        "231bceede84b039f3db0b6c0ee566b8b0d46b43cda7b1301b8d28067aaeafed9",
    },
    {
      name: "get_document_import_capabilities",
      schemaSha256:
        "c5104925f7169ab057cacf5d2bfc6c2f31080a0789ee25a170187d3a434205a7",
    },
    {
      name: "list_documents",
      schemaSha256:
        "52d8b14d43055d3fa0c9827ba0641c6a2f990d46abacf301bce57686043eadcf",
    },
    {
      name: "export_document_chunk",
      schemaSha256:
        "34e05b0312482b840a0a93a4df4c36bd5d24d4907c65d8b7b33555eab62222e9",
    },
    {
      name: "create_application",
      schemaSha256:
        "23f9a2916dbb146969d4808ca440bd3091b4e6973dad64114270faa1d68ae5ae",
    },
    {
      name: "update_application",
      schemaSha256:
        "966c5ff26deb392f73f6776eef0712982ab864740a00585df7a2c0ec87add6a5",
    },
    {
      name: "bulk_update_applications",
      schemaSha256:
        "9f7dc1cf9c7a5561d9e727e711c5c750256bea3cdc0fef3ceb59188910675b3e",
    },
    {
      name: "add_application_event",
      schemaSha256:
        "c270ac544cb4c8cb1661b2ddfda53ee050d9b96dd4b9393c6d7365e6c966cdf5",
    },
    {
      name: "delete_application",
      schemaSha256:
        "62d287d8013df8eb3946e140c9fa181f1b88cf1e22c4aec7a11c473b1418dd0c",
    },
    {
      name: "upsert_application_from_email",
      schemaSha256:
        "ca3ed5e2101fd9edd9b66d39d967ab893e1d59d8ce7f856782f08998f39dc77f",
    },
    {
      name: "begin_document_import",
      schemaSha256:
        "cee8c2d946d3559248d53bfa74609400c5f2a798d439feaae9b40c1f79af455b",
    },
    {
      name: "append_document_chunk",
      schemaSha256:
        "fba05351b4cfce5e5b534506760904722a2f0b36f5472f21cfa5e1847bb88ccb",
    },
    {
      name: "complete_document_import",
      schemaSha256:
        "f065dd93848f10e537a5b1a3a1527d7d16b0933b0c6ec70fcd0dfff96c706324",
    },
    {
      name: "cancel_document_import",
      schemaSha256:
        "3fabd73b3486a85acaf255f4e91bf1fee264f58f7c85c58f6012e07bcd5ad9ff",
    },
  ],
} as const;
