// Generated by scripts/generate-mcp-schema.mjs. Do not edit by hand.
export const applicationMcpSchemaManifest = {
  schemaSha256:
    "38de94b7071a8146b182be148b06fcf6e6f4c947aee78cfee8a34a0560163906",
  schemaVersion: 10,
  toolCount: 31,
  tools: [
    {
      name: "get_tracker_context",
      schemaSha256:
        "1af96f567c6ff545efab82a8839a689979fba1767b939c37eb71e9d166b14a27",
    },
    {
      name: "get_connector_schema_status",
      schemaSha256:
        "81e1d50aa1240d64a013cfc05ffff4efb1db7e4f9396279085ebf3eea6e2b633",
    },
    {
      name: "get_job_search_summary",
      schemaSha256:
        "5eb7e6a956eb8bea6910803275f48c2a6b3bfb9f5be3831bfb2c31f93f48b2ff",
    },
    {
      name: "list_applications",
      schemaSha256:
        "b733a3ae8501112ff170c53718f79f7217335f57a7d75f36cd3f27c4a646a942",
    },
    {
      name: "get_application",
      schemaSha256:
        "b6236c81775ecc5bb72f4581d459996bc468cd15d17d4ce7a81de86948cbf6a2",
    },
    {
      name: "list_unlinked_applications",
      schemaSha256:
        "5ec64a843a14055035f1645ef5a520b37f8fcc42d2e3395db1530e7c1f728e09",
    },
    {
      name: "get_application_data_quality",
      schemaSha256:
        "c9b62bb6d66374df41ea4bf1b8ffae6fa4e7e6c243b6fbaa692acd256af7bbf9",
    },
    {
      name: "audit_duplicate_applications",
      schemaSha256:
        "9d22f5af2e73e197717a8f5dc5dd4e1dd7b1fb021b7dea1d9ca4b28d3499610c",
    },
    {
      name: "find_duplicate_applications",
      schemaSha256:
        "fd8050e13554e6426dfc562a88cdb7b2e581de7148798fa0b27fa2d6e7fe739f",
    },
    {
      name: "merge_applications",
      schemaSha256:
        "c0e4eec78ff1aced79efb96116a4c3ec987d3949eaf3354cdf54338cfe21dfee",
    },
    {
      name: "match_job_application_email",
      schemaSha256:
        "efe1536e9baca7035aab7963b1cb1dfcf158c38fdbdea6587b9819116503487d",
    },
    {
      name: "link_email_evidence",
      schemaSha256:
        "a4b8cf7c00582510235b7033cd5b6cdb624a8d46f6d8268d6fc77e21c16734c1",
    },
    {
      name: "reconcile_application_from_evidence",
      schemaSha256:
        "dbc678bf5cc5caf9a64d67509eae2fd006bbb31ede2ca3e9c05238d01239f835",
    },
    {
      name: "sync_outlook_email_evidence",
      schemaSha256:
        "42713832820b5942635b8de2c59a6f9dd5a59707c09fb9f15dff7b07a44a2094",
    },
    {
      name: "extract_job_links",
      schemaSha256:
        "a5f87d552d52f1fcfd2ee23a2f81b2d8cdeb8f0e12bcbc94e927821b144f703c",
    },
    {
      name: "resolve_job_links",
      schemaSha256:
        "c0db14d7f90e6154f9130df7e517c5d74a880c913172ac12a02e2c03c64d18b2",
    },
    {
      name: "inspect_job_posting",
      schemaSha256:
        "ba93b8e2e61c88c122fed120fdb6aeb5b8e2106dabc07a4becfdd7c5e1cd7f83",
    },
    {
      name: "get_reference_data",
      schemaSha256:
        "231bceede84b039f3db0b6c0ee566b8b0d46b43cda7b1301b8d28067aaeafed9",
    },
    {
      name: "get_document_import_capabilities",
      schemaSha256:
        "c5104925f7169ab057cacf5d2bfc6c2f31080a0789ee25a170187d3a434205a7",
    },
    {
      name: "list_documents",
      schemaSha256:
        "52d8b14d43055d3fa0c9827ba0641c6a2f990d46abacf301bce57686043eadcf",
    },
    {
      name: "export_document_chunk",
      schemaSha256:
        "34e05b0312482b840a0a93a4df4c36bd5d24d4907c65d8b7b33555eab62222e9",
    },
    {
      name: "create_application",
      schemaSha256:
        "eacecd0f2e8afa0fb3179f97c6a3729c9a6cd5d7c68d0ed696d737179942bf43",
    },
    {
      name: "update_application",
      schemaSha256:
        "0f6600649b45b40a7e43c2eccde069f291a27e93ba345977a3ed48d331b42652",
    },
    {
      name: "bulk_update_applications",
      schemaSha256:
        "14794fc204ae8d3f14d1b6f530ef239bcf3e4a0edd309f792d849f76b540b264",
    },
    {
      name: "add_application_event",
      schemaSha256:
        "68beca6c84a5b4f3d94f14959fb4fb4fadc0e547b9ea78c6e417aaa3514c760b",
    },
    {
      name: "delete_application",
      schemaSha256:
        "62d287d8013df8eb3946e140c9fa181f1b88cf1e22c4aec7a11c473b1418dd0c",
    },
    {
      name: "upsert_application_from_email",
      schemaSha256:
        "0be5d8a856c1ef9802f234fc3099e6a044c27f840cc411a4d0a2881c3947a98c",
    },
    {
      name: "begin_document_import",
      schemaSha256:
        "cee8c2d946d3559248d53bfa74609400c5f2a798d439feaae9b40c1f79af455b",
    },
    {
      name: "append_document_chunk",
      schemaSha256:
        "fba05351b4cfce5e5b534506760904722a2f0b36f5472f21cfa5e1847bb88ccb",
    },
    {
      name: "complete_document_import",
      schemaSha256:
        "f065dd93848f10e537a5b1a3a1527d7d16b0933b0c6ec70fcd0dfff96c706324",
    },
    {
      name: "cancel_document_import",
      schemaSha256:
        "3fabd73b3486a85acaf255f4e91bf1fee264f58f7c85c58f6012e07bcd5ad9ff",
    },
  ],
} as const;
