// Generated by scripts/generate-mcp-schema.mjs. Do not edit by hand.
export const applicationMcpSchemaManifest = {
  schemaSha256:
    "d0444cb2197bd67a34b07d8f1fd36b35bba530bd42da5ab28885248637113423",
  schemaVersion: 18,
  toolCount: 36,
  tools: [
    {
      name: "get_tracker_context",
      schemaSha256:
        "1af96f567c6ff545efab82a8839a689979fba1767b939c37eb71e9d166b14a27",
    },
    {
      name: "get_connector_schema_status",
      schemaSha256:
        "81e1d50aa1240d64a013cfc05ffff4efb1db7e4f9396279085ebf3eea6e2b633",
    },
    {
      name: "get_job_search_summary",
      schemaSha256:
        "5eb7e6a956eb8bea6910803275f48c2a6b3bfb9f5be3831bfb2c31f93f48b2ff",
    },
    {
      name: "list_applications",
      schemaSha256:
        "b733a3ae8501112ff170c53718f79f7217335f57a7d75f36cd3f27c4a646a942",
    },
    {
      name: "get_application",
      schemaSha256:
        "a14113c231697f65024e44dae1ea7ac1cdc3abd5d7f73067dbac26a73534ad5a",
    },
    {
      name: "list_application_events",
      schemaSha256:
        "79e524453ce6d59bbd68663c8163cd5678eb58654eff7987820968e194e807e0",
    },
    {
      name: "list_unlinked_applications",
      schemaSha256:
        "5ec64a843a14055035f1645ef5a520b37f8fcc42d2e3395db1530e7c1f728e09",
    },
    {
      name: "get_application_data_quality",
      schemaSha256:
        "c9b62bb6d66374df41ea4bf1b8ffae6fa4e7e6c243b6fbaa692acd256af7bbf9",
    },
    {
      name: "audit_duplicate_applications",
      schemaSha256:
        "9d22f5af2e73e197717a8f5dc5dd4e1dd7b1fb021b7dea1d9ca4b28d3499610c",
    },
    {
      name: "find_duplicate_applications",
      schemaSha256:
        "fd8050e13554e6426dfc562a88cdb7b2e581de7148798fa0b27fa2d6e7fe739f",
    },
    {
      name: "merge_applications",
      schemaSha256:
        "869422df3712a8c060189a3ff2b22184f985d0012474ddc6d44319545b329f2a",
    },
    {
      name: "match_job_application_email",
      schemaSha256:
        "efe1536e9baca7035aab7963b1cb1dfcf158c38fdbdea6587b9819116503487d",
    },
    {
      name: "link_email_evidence",
      schemaSha256:
        "e2f84c96b4f96a39ea5b0f7eda76112660437f8f062242890b102c53c0568835",
    },
    {
      name: "reconcile_application_from_evidence",
      schemaSha256:
        "3999131f97ae553e17066413a2d4c8aaefac5e124059556ed3f902ef35352da9",
    },
    {
      name: "sync_outlook_email_evidence",
      schemaSha256:
        "7f364ae6c90d41b6c1ff86a637d75108ea0c431bbc23b3f55f8177d83975d3e4",
    },
    {
      name: "reconcile_outlook_graph_connection",
      schemaSha256:
        "e01bd5c8133bfdc065af8d6466cefea9916ce1d4237651e0f67012cfb65bac10",
    },
    {
      name: "search_outlook_job_digests",
      schemaSha256:
        "97e36bdf051b5c789b681fc4a2662335ac21126cd0510d2f9de09f2370219ed2",
    },
    {
      name: "process_outlook_job_digest",
      schemaSha256:
        "fa9f7ae63ce5a344f334371d530be4fb0bd721369ca2a5b593b8f89106670118",
    },
    {
      name: "extract_job_links",
      schemaSha256:
        "a5f87d552d52f1fcfd2ee23a2f81b2d8cdeb8f0e12bcbc94e927821b144f703c",
    },
    {
      name: "resolve_job_links",
      schemaSha256:
        "c0db14d7f90e6154f9130df7e517c5d74a880c913172ac12a02e2c03c64d18b2",
    },
    {
      name: "inspect_job_posting",
      schemaSha256:
        "096c36d71c5c129434c52dea1aadb65cdf308eb013722677901f8a0ee3e1816b",
    },
    {
      name: "get_reference_data",
      schemaSha256:
        "231bceede84b039f3db0b6c0ee566b8b0d46b43cda7b1301b8d28067aaeafed9",
    },
    {
      name: "get_document_import_capabilities",
      schemaSha256:
        "c5104925f7169ab057cacf5d2bfc6c2f31080a0789ee25a170187d3a434205a7",
    },
    {
      name: "list_documents",
      schemaSha256:
        "52d8b14d43055d3fa0c9827ba0641c6a2f990d46abacf301bce57686043eadcf",
    },
    {
      name: "export_document_chunk",
      schemaSha256:
        "34e05b0312482b840a0a93a4df4c36bd5d24d4907c65d8b7b33555eab62222e9",
    },
    {
      name: "create_application",
      schemaSha256:
        "eacecd0f2e8afa0fb3179f97c6a3729c9a6cd5d7c68d0ed696d737179942bf43",
    },
    {
      name: "update_application",
      schemaSha256:
        "0f6600649b45b40a7e43c2eccde069f291a27e93ba345977a3ed48d331b42652",
    },
    {
      name: "bulk_update_applications",
      schemaSha256:
        "14794fc204ae8d3f14d1b6f530ef239bcf3e4a0edd309f792d849f76b540b264",
    },
    {
      name: "add_application_event",
      schemaSha256:
        "034a1d58ed01657fe84fa6da6d39d2e4e01322478ecd98019814f4ad189757d1",
    },
    {
      name: "add_application_activity",
      schemaSha256:
        "d0e16f9368fe30a900053108de7737be249aa6249b53e3877ea28b35d01b70ad",
    },
    {
      name: "delete_application",
      schemaSha256:
        "62d287d8013df8eb3946e140c9fa181f1b88cf1e22c4aec7a11c473b1418dd0c",
    },
    {
      name: "upsert_application_from_email",
      schemaSha256:
        "6c5f5e2a1803add380938ccd2a2748d3b4c52b7327e2877c739ef51c33d660a6",
    },
    {
      name: "begin_document_import",
      schemaSha256:
        "cee8c2d946d3559248d53bfa74609400c5f2a798d439feaae9b40c1f79af455b",
    },
    {
      name: "append_document_chunk",
      schemaSha256:
        "fba05351b4cfce5e5b534506760904722a2f0b36f5472f21cfa5e1847bb88ccb",
    },
    {
      name: "complete_document_import",
      schemaSha256:
        "f065dd93848f10e537a5b1a3a1527d7d16b0933b0c6ec70fcd0dfff96c706324",
    },
    {
      name: "cancel_document_import",
      schemaSha256:
        "3fabd73b3486a85acaf255f4e91bf1fee264f58f7c85c58f6012e07bcd5ad9ff",
    },
  ],
} as const;
